apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: flux-system
data:
  datasources.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: prometheus
      - name: loki
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server
      isDefault: true
      editable: true
      version: 1
    - name: loki
      type: loki
      access: proxy
      url: http://loki:3100
      isDefault: false
      editable: true
      version: 1
