---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ingress
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: feature/validation
  url: https://github.com/kubernetes

