apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2021-03-17T17:53:22Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:phase: {}
    manager: kubectl
    operation: Update
    time: "2021-03-17T17:53:22Z"
  name: test
  resourceVersion: "34140"
  uid: 42624ca5-060f-4b8d-84bb-90036e789d0c
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
