---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: realtimeapp
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/overlays/prd
  prune: true
  sourceRef:
    kind: GitRepository
    name: realtimeapp
  validation: client

