---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cadvisor
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/kubernetes/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: cadvisor
  validation: client