---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: workshopmanagementapi
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./workshopmanagementapi/base/
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitstop-infra
  validation: client

