apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - clusterrole.yaml
  - daemonset.yaml
  - rolebinding.yaml
  - serviceAccount.yaml
configMapGenerator:
  - name: promtail-config
    files:
      - promtail.yaml