apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - podsecuritypolicy.yaml
  - role.yaml
  - rolebinding.yaml
  - secret.yaml
  - service-headless.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml