apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki-loki
  namespace: default
  labels:
    app: loki
    chart: loki-2.5.2
    heritage: Helm
    release: loki
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [loki-loki]