apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki-loki
  namespace: default
  labels:
    app: loki
    chart: loki-2.5.2
    heritage: Helm
    release: loki
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki-loki
subjects:
- kind: ServiceAccount
  name: loki-loki