apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: loki
    chart: loki-2.5.2
    heritage: Helm
    release: loki
  annotations:
    {}
  name: loki-loki
  namespace: default
automountServiceAccountToken: true