---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: wordpress-prod
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/static/provider/cloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: ingress
  validation: client

