apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: loki-stack
spec:
  interval: 10m0s
  url: https://prometheus-community.github.io/helm-charts

