apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: loki-stack
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: '6.13.6'
      values:
        dashboardsConfigMaps: 'grafana-dashboards'
  interval: 10m0s  