---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: '>4.0.0'
  interval: 10m0s
  values:
    grafana.enabled: true
    prometheus.alertmanager.persistentVolume.enabled: false
    prometheus.enabled: true
    prometheus.server.persistentVolume.enabled: false

