apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki-stack
configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
      - dashboards/custom-dashboard.json

