apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki-stack
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: '2.4.1'
  values:
    grafana.enabled: true
    prometheus.enabled: true
  interval: 10m0s
  