---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wordpress-dev
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: development
    tag: dev
  secretRef:
    name: github-pat
  url: https://github.com/marcoippel/k8s-wordpress

