apiVersion: v1
data:
  config.yaml: |
    rules:
    - seriesQuery: 'http_requests_total'
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
kind: ConfigMap
metadata:
  labels:
    app: prometheus-adapter
    app.kubernetes.io/managed-by: Helm
  name: prometheus-adapter
  namespace: monitoring
